package.path='./Scripts/?.lua;'..package.path
local MC=require('mc')
local Objects=require('mc.objects')
local Widget=require('mc.widget')
assert(MC.valid==Objects.valid and MC.parent==Objects.parent)
assert(MC.load('objects')==Objects)
assert(MC('widget')==Widget and MC.load('widget')==Widget)
local ok,why=pcall(MC.load,'missing')
assert(not ok and tostring(why):find('unknown MC helper',1,true))
local directory=assert(os.getenv('MCT_TEST_DIR'),'MCT_TEST_DIR required')
local function write(name,content)
    local file=assert(io.open(directory..'/'..name,'wb'))
    assert(file:write(content))
    assert(file:close())
end
write('mc_sample.lua','return {name="sample"}\n')
write('entry.lua','local value=require("mc").template("sample"); return value\n')
assert(assert(loadfile(directory..'/entry.lua'))().name=='sample')
write('entry.lua','local value=require("mc").template("mc_sample.lua"); return value\n')
assert(assert(loadfile(directory..'/entry.lua'))().name=='sample')
write('custom.lua','return {name="custom"}\n')
write('entry.lua','local value=require("mc").template("custom.lua"); return value\n')
assert(assert(loadfile(directory..'/entry.lua'))().name=='custom')
ok,why=pcall(MC.template,'../sample')
assert(not ok and tostring(why):find('simple file stem',1,true))
ok,why=pcall(MC.template,'../sample.lua')
assert(not ok and tostring(why):find('simple Lua filename',1,true))
print('PASS: public MC object, widget, and sibling template helpers')
